# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: vlopatovskij@bk.ru
author_name: Vladislav Lopatovskii
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_todo
project_short_description: Pop up your to-do's in opened notebook.
python_name: jupyterlab_todo
repository: ''
test: true

